name: Clang Format Checker
on: push
jobs:
  format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1
        with:
          sources: skim.cxx
